name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild
    - name: Test
      run: xcodebuild test -project GuessNumberGame.xcodeproj -scheme GuessNumberGame -destination 'platform=macOS'
