name: Swift

on: [push]

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing
      run: xcodebuild -list
    - name: Build
      run: xcodebuild
    - name: Test
      run: xcodebuild test -project GuessNumberGame.xcodeproj -scheme GuessNumberGameTests -destination 'platform=macOS'
