name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Run
      run: xcodebuild test -project GuessNumberGame.xcodeproj -scheme GuessNumberGame -destination 'platform=OS X,arch=x86_64'
